update workflows-tester100

diff --git a/.github/workflows/workflow-tester100-2.yml b/.github/workflows/workflow-tester100-2.yml
--- a/.github/workflows/workflow-tester100-2.yml
+++ b/.github/workflows/workflow-tester100-2.yml
@@ -11,7 +11,7 @@ jobs:
       - name: Step 1
         run: echo "This step will succeed"
       - name: Step 2
-        run: exit 1  # This step will fail, but the job will continue
+        run: exit 1  # This step will fail, and the job won't continue
 
   run-ui-tests:
     name: Android Tests
